create table customers
(
    id int generated by default as identity primary key,
    name varchar(100) not null,
    surname varchar(100) not null,
    age int check (age > 18),
    phone_number varchar(30)
);

create table orders
(
    id serial primary key not null,
    date timestamp default now(),
    customer_id int not null references customers(id),
    product_name varchar(250) not null ,
    amount int check (amount > 0),
);
